/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./worker-configuration.d.ts --include-runtime false` (hash: 22d9ec51b202bd6e38db9236c0b3bde0)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./server");
  }
  interface Env {
    DB: D1Database;
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_URL: string;
    CORS_ORIGIN: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "BETTER_AUTH_SECRET"
      | "BETTER_AUTH_URL"
      | "CORS_ORIGIN"
      | "GOOGLE_CLIENT_ID"
      | "GOOGLE_CLIENT_SECRET"
      | "GITHUB_CLIENT_ID"
      | "GITHUB_CLIENT_SECRET"
    >
  > {}
}
